spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tPWYrjKxnRV9hH52E7m
      secret-key: pnfJBuDANRyVMJULPqSqzbeeogm903
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: zy-mall-shopping
  application:
    name: mall-third-party

server:
  port: 30000
